= Stage en Théorie de la décision : Exploration expérimentale du jugement délibéré sur la décision d’établir une cantine scolaire végane

Proposition de stage de Master 2

La théorie de la décision se concentre sur les notions de croyances et de préférences. Ici, nous voulons explorer le rôle négligé que l’argumentation peut jouer dans l’aide à la décision. À ce sujet, nous avons proposé un cadre théorique (Cailloux et Meinard 2019) d’exploration du jugement délibéré d’un individu soumis à un choix. Nous voulons utiliser ce cadre théorique sur le cas d’étude de l’établissement (ou non) d’une cantine scolaire végane en France. Ce thème participe de questionnements sociétaux actuels sur la place des plats plus végétalisés. Le dispositif expérimental implique de soumettre un grand nombre d’individus aux arguments de deux experts opposés sur cette question via des vidéos publiées en ligne et présentant leurs arguments et les contre-arguments qu’ils opposent à leur adversaire. L’objectif de ce dispositif est double, à la fois de réaliser une expérience susceptible de révéler à l’individu testé son jugement délibéré sur la question et, de l’autre, de mesurer l’effet de changement de son opinion par le passage par une telle expérience. 

L’étudiant.e qui joindrait ce projet aura pour responsabilité de mettre en place une telle expérimentation. Aidé.e de l’équipe de recherche, l’étudiant.e devra notamment définir une procédure participative de choix des deux experts pour garantir leur légitimité sur le sujet. Il ou Elle procédera ensuite à la collecte et la structuration des arguments des deux intervenants par entretien et réalisation de vidéos présentant les arguments. Enfin, il sera réalisé un premier test du dispositif sur un premier échantillon d’individus afin de calibrer l’expérience. Cette première analyse permettra de finaliser le protocole pour l’appliquer à un plus large échantillon.

L’équipe de recherche offre un cadre stimulant pour un étudiant intéressé par la recherche et désireux d’explorer expérimentalement des hypothèses théoriques liées à la prise de décision en général, et à la prise de décision sur les régimes alimentaires en particulier. Ce master est idéal pour un étudiant intéressé de travailler dans un cadre interdisciplinaire (sciences informatiques, aide à la décision, transition alimentaire). L’étudiant.e de master sera accueilli.e au printemps 2020 à l’université Paris Dauphine dans le laboratoire LAMSADE.

Nous cherchons un.e étudiant.e réalisant un master 2 en lien avec cette recherche, par exemple en sciences cognitives, en nutrition, ou en sciences informatiques. De bonnes connaissances en mathématique et en programmation sont un plus. Envoyer cv et lettre de motivation à Olivier Cailloux (olivier.cailloux@dauphine.fr), copies à Yves Meinard (yves.meinard@lamsade.dauphine.fr) et Nicolas Salliou (nsalliou@ethz.ch). Plus d’informations par ce même biais.

== Référence
Cailloux, Olivier, and Yves Meinard. 2019. ‘A Formal Framework for Deliberated Judgment’. Theory and Decision. https://doi.org/10.1007/s11238-019-09722-7, https://arxiv.org/abs/1801.05644.

